FROM python:3.9

ENTRYPOINT ["bash"]

# Commands to execute on bash to first build an image named pandas with the tag test, using the Dockerfile and then run the image to start the container
# docker build -t py:hw1 .
# docker run -it py:hw1